### PR TITLE
Add  Yeelight 1S Lightstrip (YLDD05Y) support

### PR DESCRIPTION
**Pull request by WouterDoornbos**

### CODE REVIEW

**Comment by syssi** [comment]
Did you test your configuration? Your update of the README says "untested!".

**Comment by WouterDoornbos** [comment]
> Did you test your configuration? Your update of the README says "untested!".

Whoops! Yes, I did test this config. Wrote an article about it on:

https://wouterdev.nl/yeelight-led-strip-1s-flash-esphome/

**Comment by syssi** [comment]
Cool! Good job! Could you update the README and fix the little lint issue the CI is complaining about. Thanks in advance!

**Comment by syssi** [comment]
Feel free to link your blog post at the README too!

**Comment by WouterDoornbos** [comment]
Thank you! One moment, i will update the readme file.

**Comment by syssi** [comment]
@WouterDoornbos I've merged the PR already but I pushed some changes first. If you want to improve something feel free to create a second PR!

**Comment by WouterDoornbos** [comment]
Thank you for your edit 😊 you were ahead of me. Have a great day

From: Sebastian Muszynski ***@***.***>
Date: Thursday, 4 November 2021 at 08:44
To: syssi/esphome-yeelight-ceiling-light ***@***.***>
Cc: WouterD ***@***.***>, Mention ***@***.***>
Subject: Re: [syssi/esphome-yeelight-ceiling-light] Add Yeelight 1S Lightstrip (YLDD05Y) support (PR #27)

@WouterDoornbos<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWouterDoornbos&data=04%7C01%7C%7C9b68ea688faf49ba30a108d99f66f320%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637716086788757558%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Pa7swNR1RAO7lLjKkLs4FXay2pzSOreLbKuEcGL%2BWqk%3D&reserved=0> I've merged the PR already but I pushed some changes first. If you want to improve something feel free to create a second PR!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsyssi%2Fesphome-yeelight-ceiling-light%2Fpull%2F27%23issuecomment-960523226&data=04%7C01%7C%7C9b68ea688faf49ba30a108d99f66f320%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637716086788767514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GBuBJwwHTOxRfKS%2FwP6b3eJcnsBhRYSASAdD4F5i3LE%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACFG2D3HQQVARIAFSOFXEXTUKI2WHANCNFSM5HJZFN2Q&data=04%7C01%7C%7C9b68ea688faf49ba30a108d99f66f320%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637716086788767514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5c2HWzA00%2FSAUlHPgMaP%2FwvxU%2BKwKXq40WP6Da2u4qQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C9b68ea688faf49ba30a108d99f66f320%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637716086788767514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tK5VMnU8qOfr7hQekni2aGgTWEltNRNtsnJnPcd9BoA%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C9b68ea688faf49ba30a108d99f66f320%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637716086788777472%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=A6Grv0a%2B9xznXweuOy%2BhvaI52rntzZLRIKEbWKbRgp8%3D&reserved=0>.

**Pull request merged**
