### PR TITLE
Fix: Pinout for yeelink.light.ceiling22

### PR DESCRIPTION
**Pull request by B48D81EFCC**
Hi,

the pinout was wrong. I was not able to flash the ESP32.
I corrected the pinout.

### CODE REVIEW

**Comment by syssi** [comment]
Could you double check the labels of the test pads? Your pull request doesn't match with this statement:

https://github.com/syssi/esphome-yeelight-ceiling-light/issues/56#issuecomment-1254033273

**Comment by B48D81EFCC** [comment]
> Could you double check the labels of the test pads? Your pull request doesn't match with this statement:
> 
> [#56 (comment)](https://github.com/syssi/esphome-yeelight-ceiling-light/issues/56#issuecomment-1254033273)

Sorry, I made a mistake in my comment (I edited the comment).
The information in the PR is correct.

**Comment by syssi** [comment]
It's normal to cross the lines if you connect an USB-to-TTL adapter. The official function of `GPIO1` of an ESP32 is `TX` and `GPIO3` is `RX`. If you connect your USB-to-TTL adapter you have to connect RX to TX, and TX to RX.

**Comment by syssi** [comment]
Let's close this PR. Because the function of the GPIO depends on the point of view.

**Pull request closed without merging**
